export const ACTIVITY_ACTIONS = {
  AUTH_REGISTERED: 'auth.registered',
  AUTH_EMAIL_VERIFIED: 'auth.email.verified',
  AUTH_SESSION_RENEWED: 'auth.session.renewed',
  AUTH_PASSWORD_RESET_REQUESTED: 'auth.password.reset.requested',
  AUTH_PASSWORD_RESET_COMPLETED: 'auth.password.reset.completed',
  AUTH_LOGOUT: 'auth.logout',
  ORG_CREATED: 'org.created',
  ORG_MEMBER_INVITED: 'org.member.invited',
  ORG_MEMBER_JOINED: 'org.member.joined',
  ORG_INVITATION_DECLINED: 'org.invitation.declined',
  PROJECT_CREATED: 'project.created',
  PROJECT_UPDATED: 'project.updated',
  PROJECT_DELETED: 'project.deleted',
  PROJECT_MEMBER_ADDED: 'project.member.added',
  PROJECT_MEMBER_REMOVED: 'project.member.removed',
  TASK_CREATED: 'task.created',
  TASK_UPDATED: 'task.updated',
  TASK_DELETED: 'task.deleted',
  TASK_STATUS_CHANGED: 'task.status.changed',
  TASK_STATUS_AUTO_COMPLETED: 'task.status.auto-completed',
  TASK_TAGS_ADDED: 'task.tags.added',
  TASK_TAGS_REMOVED: 'task.tags.removed',
  TASK_ATTACHMENT_ADDED: 'task.attachment.added',
  ADMIN_USER_BANNED: 'admin.user.banned',
  ADMIN_USER_UNBANNED: 'admin.user.unbanned',
  ADMIN_USER_RESTORED: 'admin.user.restored',
  ADMIN_USER_PROMOTED: 'admin.user.promoted',
  ADMIN_TASK_RESTORED: 'admin.task.restored',
  ADMIN_ORG_PLAN_OVERRIDDEN: 'admin.org.plan_overridden',
} as const;

export type ActivityAction = (typeof ACTIVITY_ACTIONS)[keyof typeof ACTIVITY_ACTIONS];
