export type ErrorCode =
  | 'EMAIL_REGISTERED'
  | 'BANNED_USER'
  | 'INSUFFICIENT_ROLE'
  | 'INVALID_TASK_TRANSITION'
  | 'PLAN_LIMIT_EXCEEDED'
  | 'RESOURCE_NOT_FOUND'
  | 'INVALID_OR_EXPIRED_TOKEN'
  | 'INVALID_CREDENTIALS'
  | 'EMAIL_NOT_VERIFIED';
